language: objective-c

osx_image: xcode9.2

script:
  - xcodebuild test -scheme Coletiv-Example -workspace ./Example/Coletiv.xcworkspace -destination "platform=iOS Simulator,name=iPhone 8,OS=11.2" | xcpretty
after_success:
  - bash <(curl -s https://codecov.io/bash)